### ISSUE TITLE
proj version 6 removes projects.h

### ISSUE THREAD

**Issue by shawnlaffan** [PDLPorters/pdla-rest#18]
The code in inc/Alien::Proj4 depends on projects.h, but this has been removed in proj version 6.  

If the interface needs this code (I have not checked) then it should be possible to lock the Alien to build proj version 4.  

It's probably worth porting inc/Alien::Proj4 into its own distro in any case as that can then be modernised to use more recent Alien::Build approaches.  

I am maintaining Alien::proj based on the alienfile approach.  The logic could be copied across to Alien::Proj4, with a one line change to set a maximum version.
https://metacpan.org/release/SLAFFAN/Alien-proj-1.02  
https://github.com/shawnlaffan/perl-alien-proj4 (the git repo needs to be renamed to drop the 4)

**Comment by mohawk2** [comment]
If you'd like to make `Alien::proj` operate well with the relevant PDLA modules, capturing the right versions, then PR that against those relevant PDLA modules, I'll be pleased to accept it.

Even better, want to split out those relevant modules into a PDLA::ProjLibs repo using the instructions I sent to pdl-devel? Note I said repo, we can figure out details like transferring the repo, giving you co-maint on the relevant modules for release purposes, etc.

If you *do* want to do that, say so and I can help you through it!

**Comment by mohawk2** [comment]
(The repo-split-out includes preserving the history, same as I'm just doing with `Inline::Pdlapp`)

**Comment by shawnlaffan** [comment]
I suspect it is better to have a separate Alien for proj4, as that will allow co-existence with one that can be upgraded to version 6 and later.  Otherwise Alien::gdal will stop working when it starts to use GDAL version 2.5, as that uses proj6 (or maybe proj5, but not proj4).  

I'd be happy to set up and maintain a repo for Alien::Proj4 under the PDL banner.  

I could have a look at the proj bindings, but have less experience wrangling such things.

**Comment by mohawk2** [comment]
I've just added you as a collaborator on the PDL `Alien::Proj4` repo. I'd suggest you stick to the existing API, such as it is. What is your plan? :-)

**Comment by shawnlaffan** [comment]
My plan is to overwrite the current implementation with an alienfile based setup directly adapted from Alien::proj.  See https://github.com/shawnlaffan/perl-alien-proj4/tree/proj4_max

It still needs a few of the API components from the current implementation, though.

**Comment by mohawk2** [comment]
Sounds great. May I suggest you open a PR on the PDLPorters repo when it's ready, for wider review? I always find my code is better after a second (or more) pair of eyes :-)

**Comment by shawnlaffan** [comment]
Closing.  Alien::Proj4 has its own repo: https://github.com/PDLPorters/Alien-Proj4
