### ISSUE TITLE
Needs perldl.conf from pdla-core, or parts of

### ISSUE THREAD

**Issue by shawnlaffan** [PDLPorters/pdla-rest#19]
The build system depends on settings from PDLA::Config, which so far as I can tell are set using perldl.conf.  That file is only in the pdla-core repo.

This means WITH_PROJ is set at the PDLA config time, whereas it is needed for parts of PDLA::Rest.

The relevant config options should be shifted across, perhaps generating %PDLA::Rest::Config instead of %PDLA::Config.  

It would also be useful if options were set when the makefile is built.  Perhaps I'm just not passing those correctly in my runs, though.

**Comment by mohawk2** [comment]
The direction of travel is to eliminate all the `WITH_PROJ` et al. You may note that all the -rest tests just stopped checking those as of about 10 hours ago.

If the module wants to know if Proj is available / should be built, it should load `Alien::Proj4` inside an eval, and fail gracefully (with `write_dummy_make("No Proj4"); return`). Please forget about `%PDLA::Config` :-)

**Comment by mohawk2** [comment]
Likewise, tests should just try to load the relevant module, and `skip_all` if that fails. See `t/lm.t` for an example. On being carved into a separate distro, obviously that would be eliminated since failing to load would not be Ok!

I'd like to leave this issue open as a reminder to finish annihilating all the config-depending stuff. Like I said, it's part of my plan.

**Comment by shawnlaffan** [comment]
OK, I'll hopefully submit a PR shortly that removes any use of the inc/Alien::Proj4 approach.

Then it would be good to separate the two proj4 dependent modules into their own repos and distros.

**Comment by mohawk2** [comment]
If they work well together, we could equally make them into one distro. I'll defer to you on whether they should be one, or two, it's not much extra work either way :-)

**Comment by shawnlaffan** [comment]
I'm in two minds as to whether they need one or two.  There are two separate makefiles at the moment, but there is a degree of overlap so perhaps they could be combined.

**Comment by mohawk2** [comment]
My concept is PDLA::GIS, with both included. I'm currently relocating all of ::Rest's `t` files into subdirectories where they more idiomatically live. Then I'll look into splitting them out!

**Comment by shawnlaffan** [comment]
Let's go with that.

**Comment by zmughal** [comment]
Closing issue as this repo is not being used for current development.
