### ISSUE TITLE
Lib/lib clash on Windows

### ISSUE THREAD

**Issue by shawnlaffan** [PDLPorters/pdla-rest#20]
The PDLA/Rest.pm file is under the lib dir, whereas all the other files are under Lib.

On Windows this creates issues as they are all lumped under the same folder, but then lib/PDLA/Rest.pm cannot be found by the main Makefile.PL.

It might only affect the version logic, though, as I cannot find any other hard coded reference to lib.

**Comment by mohawk2** [comment]
I was aware of this a number of years ago, which was why (in a branch of legacy PDL) I renamed Lib to Libtmp. I think I need to do that here as well! Watch this space.

**Comment by mohawk2** [comment]
As you can see, I've pushed a commit that renames Lib to Libtmp. Please try again!
