### ISSUE TITLE
Convert module namespace: s|PDL|PDLA|

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdla-rest#3]
- the badges and meta info will both need to change as well

**Comment by devel-chm** [comment]
How about using PDL::Agile rather than polluting a top level namespace?  We can then alias that to PDLA.

**Comment by zmughal** [comment]
Definitely worth considering. So all the functions would sit under `*PDL::Agile`?

**Comment by devel-chm** [comment]
Yes, and we could alias that to *PDLA if we don't want to type so much.

**Comment by mohawk2** [comment]
Considered. No.

**Comment by mohawk2** [comment]
Issues dealt with so far: had to rename a few files/dirs from `PDL*` to `PDLA*`.

`m51.fits` and the FITS code had problems because the file-format relies on byte alignment / fixed field size and PDLA is more bytes than PDL.

**Comment by mohawk2** [comment]
Currently-failing tests:

```
t/proj_transform.t            (Wstat: 256 Tests: 1 Failed: 0)
  Non-zero exit status: 1
  Parse errors: Bad plan.  You planned 299 tests but ran 1.
t/storable.t                  (Wstat: 65280 Tests: 5 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 23 tests but ran 5.
t/subclass.t                  (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 6 tests but ran 0.
t/subclass2.t                 (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 14 tests but ran 1.
t/subclass3.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 7 tests but ran 0.
t/subclass4.t                 (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 8 tests but ran 0.
```

**Comment by mohawk2** [comment]
The subclassing ones were solved by switching `Basic/Core/pdlcore.c.PL` to use `hv_fetchs` instead of `hv_fetch`.

**Comment by mohawk2** [comment]
Storable one was due to supplied test data files having a leading length byte before "PDLA" not having been updated, plus space-padding after `PDLA_*` needing adjustment.

**Comment by mohawk2** [comment]
`proj_transform.t` one was also a data alignment problem: `Lib/Transform/Cartography/earth_coast.vec.fits`.

We should have an xt test that searches for all `.fits` files and does a quick load to make sure they're valid.

**Comment by mohawk2** [comment]
@devel-chm I'm quite enjoying the irony of you being against polluting a top-level namespace while PDL claims to provide a module called (and this is its full name): `XS`. https://metacpan.org/source/CHM/PDL-2.013/Basic/Gen/PP/XS.pm

This is one of the problems PDLA will be fixing shortly: #4

**Comment by devel-chm** [comment]
Ed, I have co-maint or better for all PDL dist so I can make releases.  And
if you'll look in the record I've been a proponent for PDL overhaul and
cleanup for some time now.  Thanks for all your hard work in this direction.

--Chris

**Comment by mohawk2** [comment]
It's a shame that all that proponent-ing hasn't lead to any identifiable activity in the last year.

**Comment by devel-chm** [comment]
wow
